# MMP""MM""YMM               .M"""bgd
# P'   MM   `7              ,MI    "Y
#      MM  .gP"Ya   ,6"Yb.  `MMb.   `7MMpdMAo.  ,pW"Wq.   ,pW"Wq.`7MMpMMMb.
#      MM ,M'   Yb 8)   MM    `YMMNq. MM   `Wb 6W'   `Wb 6W'   `Wb MM    MM
#      MM 8M""""""  ,pm9MM  .     `MM MM    M8 8M     M8 8M     M8 MM    MM
#      MM YM.    , 8M   MM  Mb     dM MM   ,AP YA.   ,A9 YA.   ,A9 MM    MM
#    .JMML.`Mbmmd' `Moo9^Yo.P"Ybmmd"  MMbmmd'   `Ybmd9'   `Ybmd9'.JMML  JMML.
#                                     MM
#                                   .JMML.
# TeaSpoon Configuration File

# Config Version Number [DO-NOT-MODIFY]
version: 11

entities:
 # Weather to register Vanilla Entities (Set to false if you're going to use a MobAI Plugin such as, PureEntitiesX etc...) or not
 register: true
 # Enable Lightning Fire & Damage
 lightningFire: true

enchantments:
 # Weather to enable & register Vanilla Enchantments (Set to false if you're going to use VanillaEnchantments plugin etc...) or not
 register: true

dimensions:
 # Enable / Disable Dimensions
 enable: true
 nether:
  levelName: "nether"
 end:
  levelName: "ender"

misc:
 # !!!   ONLY ENABLE THIS IF YOU ARE SURE THAT ALL YOUR    !!!
 # !!! PLUGINS ARE COMPATIBLE WITH YOUR CURRENT PMMP BUILD !!!
 loadAllAPIs: false
 # Enable to dis-allow chest and container interactions when in creative
 limitedCreative: true
 
enderPearl:
 cooldown: 2
 damage: 5

chorusFruit:
 cooldown: 2

weather: 
 enable: true
 # Minimum Weather Duration (IN TICKS)
 minDuration: 6000
 # Maximum Weather Duration (IN TICKS)
 maxDuration: 12000
 # If lightning should be spawned in stormy weather
 lightning: true

# Redstone System
redstone:
 enable: true